import pandas as pd
import logging
from pathlib import Path
from sqlalchemy import create_engine, text

logger = logging.getLogger(__name__)
project_root = Path(__file__).resolve().parent.parent

# Create database engine
def db_engine(connection_str:str):
    return create_engine(connection_str)

# For Creating Schemas Databases
def init_db(engine):
    with engine.connect() as conn:
        conn.begin() #Start Transactions
        try:
            conn.execute(text("""
            CREATE TABLE IF NOT EXISTS dim_customers (
                customerid INT PRIMARY KEY,
                country VARCHAR(50)
            )
            """))

            conn.execute(text("""
            CREATE TABLE IF NOT EXISTS dim_products (
                stockcode VARCHAR(20) PRIMARY KEY,
                description VARCHAR(100)
            )
            """))

            conn.execute(text("""
            CREATE TABLE IF NOT EXISTS fact_transactions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                invoiceno VARCHAR(20),
                stockcode VARCHAR(20),
                quantity INT,
                unitprice FLOAT,
                totalprice FLOAT,
                invoicedate TIMESTAMP,
                customerid INT,
                country VARCHAR(50),
                FOREIGN KEY (customerid) REFERENCES dim_customers(customerid),
                FOREIGN KEY (stockcode) REFERENCES dim_products(stockcode)
            )
            """))
            conn.commit()
            logger.info("Database initialized successfully")
        except Exception as e:
            logger.error(f"Error initializing database: {str(e)}")
            conn.rollback() #Not Create Tables/Schemas When Have A Errors
            raise

# Load Dimensions Data to Database
def load_dimensions(df: pd.DataFrame, engine):
    logger.info("Loading Dimensions Tables...")

    # Convert DataFrame columns to lowercase to match PostgreSQL
    df_clean = df.copy()
    df_clean.columns = df_clean.columns.str.lower()

    # Extract Unique Columns Of Customers
    dim_customers = df_clean[["customerid", "country"]].dropna(subset=["customerid"]).drop_duplicates(subset=["customerid"])
    dim_customers["customerid"] = dim_customers["customerid"].astype(int)

    # Extract Unique Columns Of Products
    dim_products = df_clean[["stockcode", "description"]].dropna(subset=["stockcode"]).drop_duplicates(subset=["stockcode"])

    with engine.connect() as conn:
        conn.begin() #Start Transactions
        try:
            # Adding New Customers To Databases POSTGREESQL
            exists_customers_raw = conn.execute(text("SELECT customerid FROM dim_customers")).fetchall()
            exists_customers = {row[0] for row in exists_customers_raw}
            new_customers = dim_customers[~dim_customers["customerid"].isin(exists_customers)]
            if not new_customers.empty:
                new_customers.to_sql("dim_customers", conn, if_exists="append", index=False, chunksize=5000)
                logger.info(f"Loaded {len(new_customers)} new customers")
            else:
                logger.info("No new customers to load")

            # Adding New Products To Databases POSTGREESQL
            exists_products_raw = conn.execute(text("SELECT stockcode FROM dim_products")).fetchall()
            exists_products = {row[0] for row in exists_products_raw}
            new_products = dim_products[~dim_products["stockcode"].isin(exists_products)]
            if not new_products.empty:
                new_products.to_sql("dim_products", conn, if_exists="append", index=False, chunksize=5000)
                logger.info(f"Loaded {len(new_products)} new products")
            else:
                logger.info("No new products to load")
                
            conn.commit()
        except Exception as e:
            logger.info(f"Load Dimensions Table Failed : {e}")
            conn.rollback()
            raise

# Load Facts Data to Database
def load_fact(df: pd.DataFrame, engine):
    logger.info("Loading Fact Table...")

    # Convert DataFrame columns to lowercase to match PostgreSQL
    df_clean = df.copy()
    df_clean.columns = df_clean.columns.str.lower()

    # Initalize columns fact_transactions for POSTGREESQL
    fact_transactions = df_clean[
        ["invoiceno", "stockcode", "quantity", "unitprice", "totalprice", "invoicedate", "customerid", "country"]
    ].dropna(subset=["customerid"])
    fact_transactions["customerid"] = fact_transactions["customerid"].astype(int)
    
    with engine.connect() as conn:
        conn.begin()
        try:
            exists_sales_raw = conn.execute(text("SELECT invoiceno, stockcode FROM fact_transactions")).fetchall()
            exists_sales = {(str(row[0]), str(row[1])) for row in exists_sales_raw}
            
            sales_tuples = list(zip(fact_transactions["invoiceno"].astype(str), fact_transactions["stockcode"].astype(str)))
            new_sales = fact_transactions[[t not in exists_sales for t in sales_tuples]]

            if not new_sales.empty:
                new_sales.to_sql("fact_transactions", conn, if_exists="append", index=False, chunksize=5000)
                logger.info(f"Loaded {len(new_sales)} new sales")
            else:
                logger.info("No new sales to load")
            conn.commit()
        except Exception as e:
            logger.info(f"Load Facts Table Failed : {e}")
            conn.rollback()
            raise

def clear_db(engine):
    with engine.connect() as conn:
        conn.begin()
        try:
            logger.info("Refresh Data POSTGREESQL")
            conn.execute(
                # TRUNCATE removes data in table without removes schema
                text("TRUNCATE TABLE fact_transactions, dim_products, dim_customers CASCADE;")
            )
            conn.commit()
        except Exception as e:
            logger.error(f"Clear Databases Error : {e}")
            conn.rollback()
            raise

def load_data(connection_str: str, df: pd.DataFrame):
    print("="*60)
    print("PHASE 3: LOADS")
    print("="*60)

    logger.info(f"Loading data...")
    engine = db_engine(connection_str)
    init_db(engine)
    clear_db(engine)
    load_dimensions(df, engine)
    load_fact(df, engine)
    logger.info("Data loaded to POSTGREESQl Is Successfully")
    
    print("="*60)
    print("LOADS IS SUCCESSFULLY")
    print("="*60)